### ISSUE TITLE
Add Callback when date changes

### ISSUE THREAD

**Issue by SalAldana** [SharifClick/svelte-touch-datepicker#5]
First, thanks for the cool component. I'm new to Svelte and wanted to add a date picker when I came across this library. I got it working but one thing I'm looking for is the ability to get a callback for when the date has changed so I can perform some other stuff with the new date. Is there something already built in that can handle this or can this be added?

**Comment by SharifClick** [comment]
Hi @SalAldana, glad to know you are using it. This plugin still (Working in progress), so lots of things to add. 
Thank you very much for your suggestion and more suggestions are welcome. 
I will have a new release of it very soon.
Cheers

**Comment by BerkinAKKAYA** [comment]
I Added It in #7

**Comment by SharifClick** [comment]
Thanks @BerkinAKKAYA , 
New version is released.
Cheers
